# -*- coding: utf-8 -*-
"""Subscription pages for the Täsch site (mirrors the Venice subscription site).

Sources (edit these, then run  python3 _build/build_legal.py):
  _build/legal/<terms|privacy|refund>/<lang>.md   title / description, ---, mini-Markdown body
  _build/legal/ui.json                             {lang: {key: text}} footer labels, cancel page, checkout texts
Writes:
  legal-terms.js, legal-privacy.js, legal-refund.js   window.LEGAL_DOC = {lang: body HTML}
  terms.html, privacy.html, refund.html, cancel-subscription.html  (English static copy, JS switches language)
  the ui.json strings into the I18N block of script.js, the "Legal" footer column on every page, sitemap entries.
Placeholders in the Markdown: {operator} {address} {email} {country} {p1} {p2} {rate}
"""
import html, json, os, re

PAD = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(PAD)
DOMAIN = "https://taesch-parking.online"
OPERATOR = "[Company name, registration number]"
OPERATOR_ADDR = "[Registered address, country]"
SUPPORT_EMAIL = "support@alpe-parking.online"          # = SUPPORT_EMAIL in script.js
LEGAL_UPDATED = "2026-10-03"
SLUGS = ["terms", "privacy", "refund"]
PAGES = [s + ".html" for s in SLUGS] + ["cancel-subscription.html"]
TEMPLATE = "arrival-car.html"

js_path = os.path.join(SITE, "script.js")
src = open(js_path, encoding="utf-8").read()
start = src.index("const I18N = ") + len("const I18N = ")
end = src.index("\n};", start) + 2
I18N = json.loads(src[start:end])
LANGS = list(I18N)
VER = re.search(r'script\.js\?v=(\d+)', open(os.path.join(SITE, "index.html"), encoding="utf-8").read()).group(1)

# prices come from the pricing code, so the terms can't drift from the checkout
arr = re.search(r"const STAY_PRICES = (\[[^\]]+\])", src).group(1)
stay = json.loads(re.sub(r",\s*\]", "]", re.sub(r"//[^\n]*", "", arr)))
fmt = lambda n: "CHF " + (str(int(n)) if float(n).is_integer() else f"{n:.2f}")
PRICES = {"{p1}": fmt(stay[0]), "{p2}": fmt(stay[1]), "{p3}": fmt(stay[2])}

UI = json.load(open(os.path.join(PAD, "legal", "ui.json"), encoding="utf-8"))
assert set(UI) == set(LANGS), set(UI) ^ set(LANGS)

def read_md(slug, l):
    raw = open(os.path.join(PAD, "legal", slug, f"{l}.md"), encoding="utf-8").read()
    head, body = raw.split("\n---\n", 1)
    meta = dict(line.split(": ", 1) for line in head.strip().splitlines())
    return meta, body

def fill(l, text):
    text = (text.replace("{operator}", OPERATOR).replace("{address}", OPERATOR_ADDR)
                .replace("{email}", SUPPORT_EMAIL).replace("{country}", I18N[l]["footer.country"]))
    for k, v in PRICES.items():
        text = text.replace(k, v)
    left = re.findall(r"\{\w+\}", text)
    assert not left, (l, left)
    return text

def md_inline(text):
    out = html.escape(text, quote=False)
    def link(m):
        label, target = m.group(1), m.group(2)
        assert target.startswith("legal:") and target[6:] in ("terms", "privacy", "refund", "cancel-subscription"), target
        return f'<a href="{target[6:]}.html">{label}</a>'
    out = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", link, out)
    out = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", out)
    return out.replace(SUPPORT_EMAIL, f'<a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>')

def md_blocks(body):
    out = []
    for block in re.split(r"\n\s*\n", body.strip()):
        lines = [x.rstrip() for x in block.strip().splitlines()]
        if lines[0].startswith("## "):
            out.append(f"<h2>{md_inline(lines[0][3:])}</h2>")
        elif all(x.startswith("- ") for x in lines):
            out.append("<ul>" + "".join(f"<li>{md_inline(x[2:])}</li>" for x in lines) + "</ul>")
        else:
            out.append(f"<p>{md_inline(' '.join(lines))}</p>")
    return "\n".join(out)

# ---------- 1. the three documents, one script per page ----------
bodies = {}
for slug in SLUGS:
    docs = {}
    for l in LANGS:
        meta, body = read_md(slug, l)
        assert meta["title"] == UI[l]["legal." + slug], (slug, l)
        docs[l] = md_blocks(fill(l, body))
    bodies[slug] = docs
    data = json.dumps(docs, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
    open(os.path.join(SITE, f"legal-{slug}.js"), "w", encoding="utf-8").write(
        f"/* generated by _build/build_legal.py from _build/legal/{slug}/*.md */\nwindow.LEGAL_DOC = {data};\n")

# ---------- 2. strings into the I18N block of script.js ----------
for l in LANGS:
    I18N[l].pop("book.terms", None)          # replaced by sub.acceptTerms (links to the Terms and the Privacy Policy)
    I18N[l].pop("book.longStay", None)       # no long-stay rate since the official price table (2026-10-03)
    I18N[l].update(UI[l])
keys = list(I18N["en"])
assert all(sorted(I18N[l]) == sorted(I18N["en"]) or set(I18N["en"]) <= set(I18N[l]) for l in LANGS)
src = src[:start] + json.dumps(I18N, ensure_ascii=False, indent=2) + src[end:]
open(js_path, "w", encoding="utf-8").write(src)

# ---------- 3. the "Legal" footer column on every page ----------
E = UI["en"]
LEGAL_COL = f"""      <div class="footer-col footer-legal">
        <h4 data-i18n="legal.heading">{E["legal.heading"]}</h4>
        <a href="terms.html" data-i18n="legal.terms">{E["legal.terms"]}</a>
        <a href="privacy.html" data-i18n="legal.privacy">{E["legal.privacy"]}</a>
        <a href="refund.html" data-i18n="legal.refund">{E["legal.refund"]}</a>
        <a href="cancel-subscription.html" data-i18n="legal.cancel">{E["legal.cancel"]}</a>
        <a href="mailto:{SUPPORT_EMAIL}">{SUPPORT_EMAIL}</a>
      </div>
"""
CONTACT = re.compile(r'(      <div class="footer-col">\s*<h4 data-i18n="footer.contact">.*?</div>\n)', re.S)

def with_footer(s):
    s = re.sub(r'      <div class="footer-col footer-legal">.*?</div>\n', "", s, flags=re.S)   # idempotent
    s, n = CONTACT.subn(lambda m: m.group(1) + LEGAL_COL, s, count=1)
    assert n == 1
    return s

# ---------- 4. the four pages, built from a sub-page template ----------
tpl = open(os.path.join(SITE, TEMPLATE), encoding="utf-8").read()
head_end = tpl.index('  <section class="section-hero">')
foot_start = tpl.index('  <footer class="site-footer">')
q = lambda x: html.escape(x, quote=False)
qa = lambda x: html.escape(x, quote=True)

def page_html(page, title_key, desc_key, body, extra_script=""):
    head = tpl[:head_end].replace(TEMPLATE, page)
    head = re.sub(r"<title>.*?</title>", f"<title>{q(E[title_key])} — Täsch Parking</title>", head)
    head = re.sub(r'<meta name="description" content="[^"]*" />', f'<meta name="description" content="{qa(E[desc_key])}" />', head)
    head = head.replace('<a href="getting-here.html" class="is-current"', '<a href="getting-here.html"')
    hero = f"""  <section class="section-hero">
    <div class="wrap">
      <nav class="breadcrumb"><a href="index.html" data-i18n="pg.nav.home">{E.get("pg.nav.home", I18N["en"]["pg.nav.home"])}</a><span>/</span><span data-i18n="{title_key}">{q(E[title_key])}</span></nav>
      <h1 data-i18n="{title_key}">{q(E[title_key])}</h1>
      <p class="article-meta"><span data-i18n="legal.updated">{E["legal.updated"]}</span><time datetime="{LEGAL_UPDATED}" data-date>{LEGAL_UPDATED}</time></p>
    </div>
  </section>
  <section class="section-body">
    <div class="wrap">
      <article class="prose legal-prose"{' id="legalBody"' if extra_script else ""}>
{body}
      </article>
    </div>
  </section>
"""
    foot = tpl[foot_start:]
    if extra_script:
        foot = foot.replace(f'  <script src="script.js?v={VER}"></script>',
                            f'  <script src="{extra_script}?v={VER}"></script>\n  <script src="script.js?v={VER}"></script>')
    return head + hero + foot

for slug in SLUGS:
    page = slug + ".html"
    out = page_html(page, "legal." + slug, f"legal.{slug}Desc", bodies[slug]["en"], f"legal-{slug}.js")
    open(os.path.join(SITE, page), "w", encoding="utf-8").write(out)

cancel_body = f"""        <p data-i18n="cancel.lead">{q(E["cancel.lead"])}</p>
        <h2 data-i18n="cancel.formH">{q(E["cancel.formH"])}</h2>
        <p data-i18n="cancel.formLead">{q(E["cancel.formLead"])}</p>
        <form class="cancel-form" id="cancelForm" novalidate>
          <label class="cf-field"><span><span data-i18n="cancel.email">{q(E["cancel.email"])}</span> *</span><input type="email" name="email" required autocomplete="email" inputmode="email" spellcheck="false" autocapitalize="off" placeholder="name@example.com"></label>
          <label class="cf-field"><span data-i18n="cancel.order">{q(E["cancel.order"])}</span><input type="text" name="order" autocomplete="off" spellcheck="false" placeholder="TS-123456"></label>
          <button type="submit" class="cf-submit"><span data-i18n="cancel.submit">{q(E["cancel.submit"])}</span></button>
          <p class="cancel-msg" id="cancelMsg" role="status" tabindex="-1" hidden></p>
        </form>
        <p data-i18n-rich="cancel.alt">{md_inline(E["cancel.alt"].replace("{email}", SUPPORT_EMAIL))}</p>
        <h2 data-i18n="cancel.afterH">{q(E["cancel.afterH"])}</h2>
        <ul><li data-i18n="cancel.after1">{q(E["cancel.after1"])}</li><li data-i18n="cancel.after2">{q(E["cancel.after2"])}</li><li data-i18n="cancel.after3">{q(E["cancel.after3"])}</li></ul>
        <p><a href="terms.html" data-i18n="legal.terms">{q(E["legal.terms"])}</a> · <a href="refund.html" data-i18n="legal.refund">{q(E["legal.refund"])}</a> · <a href="privacy.html" data-i18n="legal.privacy">{q(E["legal.privacy"])}</a></p>"""
open(os.path.join(SITE, "cancel-subscription.html"), "w", encoding="utf-8").write(
    page_html("cancel-subscription.html", "legal.cancel", "cancel.lead", cancel_body))

pages = sorted(f for f in os.listdir(SITE) if f.endswith(".html"))
for f in pages:
    p = os.path.join(SITE, f)
    s = open(p, encoding="utf-8").read()
    open(p, "w", encoding="utf-8").write(with_footer(s))

# ---------- 5. sitemap ----------
sm_path = os.path.join(SITE, "sitemap.xml")
sm = open(sm_path, encoding="utf-8").read()
sm = re.sub(r"  <url>\n    <loc>[^<]*/(?:terms|privacy|refund|cancel-subscription)\.html[^<]*</loc>.*?</url>\n", "", sm, flags=re.S)
def url_of(page, l):
    return f"{DOMAIN}/{page}" + ("" if l == "en" else f"?lang={l}")
blocks = []
for page in PAGES:
    alts = "\n".join(f'    <xhtml:link rel="alternate" hreflang="{l}" href="{html.escape(url_of(page, l))}"/>' for l in LANGS)
    alts += f'\n    <xhtml:link rel="alternate" hreflang="x-default" href="{url_of(page, "en")}"/>'
    for l in LANGS:
        blocks.append(f"  <url>\n    <loc>{html.escape(url_of(page, l))}</loc>\n{alts}\n  </url>\n")
sm = sm.replace("</urlset>", "".join(blocks) + "</urlset>")
open(sm_path, "w", encoding="utf-8").write(sm)

print(f"ok: {len(LANGS)} languages, {len(keys)} I18N keys, pages {PAGES}, footer on {len(pages)} pages, v={VER}")
